# Generated by Django 4.0.1 on 2022-01-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
    ]
