# Generated by Django 4.0.1 on 2022-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userinfo_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='123456', max_length=32),
        ),
    ]
