# Generated by Django 4.0.1 on 2022-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_userinfo_majr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='majr',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
