# Generated by Django 4.0.1 on 2022-01-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_userinfo_majr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
