# Generated by Django 4.0.1 on 2022-02-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_userinfo_pwd_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '注册用户', 'verbose_name_plural': '注册用户'},
        ),
    ]
